applications:
  argocd:
    path: applications/argocd  
    namespace: argocd
  cert-manager:
    path: applications/cert-manager
    namespace: gateway
  external-dns:
    path: applications/external-dns
    namespace: gateway
  harbor:
    path: applications/harbor
    namespace: harbor
  keycloak:
    path: applications/keycloak
    namespace: keycloak
  longhorn:
    path: applications/longhorn
    namespace: longhorn-system
  metallb:
    path: applications/metallb
    namespace: metallb-system
  traefik:
    path: applications/traefik
    namespace: gateway
  wiemansite:
    path: applications/wiemansite
    namespace: default