environment:
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example

nextcloud:
  nextcloud:
    host: example.com

    # Extra config files created in /var/www/html/config/
    # ref: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#multiple-config-php-file
    configs:
