apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: prevent-sync
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - image: itzg/rcon-cli:1.7.3
        name: prevent-sync
        command:
          - sh
          - -c
          - |
            players=$(rcon-cli list | grep -oP 'There are \K\d+')
            echo "Players online: $players"
            [ "$players" -gt 0 ] && exit 1 || exit 0
        env:
          - name: RCON_HOST
            value: minecraft-rcon
          - name: RCON_PASSWORD
            valueFrom:
              secretKeyRef:
                key: rcon-password
                name: minecraft-rcon

      restartPolicy: Never