apiVersion: v1
kind: ConfigMap
metadata:
  name: whitelist
data:
  whitelist.json: |
    [
      {
        "uuid": "b7adf8b9-3f07-4fc8-ab03-edc5f672b611",
        "name": "wiemanboy"
      },
      {
        "uuid": "392136e0-63c4-49e9-9d79-6e9a24ee3992",
        "name": "Yeeeesh"
      },
      {
        "uuid": "8f0d7936-2951-4f09-be34-3a84ad8f75b2",
        "name": "brickyricky"
      },
      {
        "uuid": "021103ab-25b6-41c1-980f-12c3817defda",
        "name": "UgandanKnuckless"
      },
      {
        "uuid": "6432592a-6513-43cb-8893-887fb5cfe0d9",
        "name": "Kartason"
      },
      {
        "uuid": "46fcaa58-3462-41c9-8dc1-c568801dc38a",
        "name": "SamSoms"
      },
      {
        "uuid": "db437baa-edbd-4620-b28a-bb06bc97b9ff",
        "name": "xxGabbieee"
      }
    ]
