apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: whitelist-reload
spec:
  template:
    spec:
      annotations:
        checksum/whitelist: {{ include (print $.Template.BasePath "/whitelist.yaml") . | sha256sum }}
      containers:
      - image: itzg/rcon-cli:1.7.3
        name: whitelist-reload
        args:
          - whitelist reload
        env:
          - name: RCON_HOST
            value: minecraft-rcon
          - name: RCON_PASSWORD
            valueFrom:
              secretKeyRef:
                key: rcon-password
                name: minecraft-rcon

      restartPolicy: Never