environment: 
  hostname: wieman.cloud
  gateway:
    name: traefik-gateway
    listener: websecure
    namespace: gateway

applications:
  website:
    deploy: true
    namespace: website

infrastructure:
  argocd:
    deploy: true
    version: 0.0.0

  cert-manager:
    deploy: true
    version: 0.0.0
    namespace: gateway

  external-dns:
    deploy: true
    version: 0.0.0
    namespace: gateway

  harbor:
    deploy: true
    version: 0.0.1
    namespace: harbor

  keycloak:
    deploy: true
    version: 0.1.0
    namespace: keycloak

  longhorn:
    deploy: true
    version: 0.0.0
    namespace: longhorn-system

  metallb:
    deploy: true
    version: 0.0.2
    namespace: metallb-system

  traefik:
    deploy: true
    version: 0.0.1
    namespace: gateway