environment: 
  hostname: wieman.cloud
  gateway:
    name: traefik-gateway
    listener: websecure
    namespace: gateway

applications:
  website:
    deploy: true
    namespace: website

infrastructure:
  argocd:
    deploy: true
    version: 0.0.0

  certManager:
    deploy: true
    version: 0.0.0

  external-dns:
    deploy: true
    version: 0.0.0
    namespace: gateway

  harbor:
    deploy: true
    version: 0.0.1
    namespace: harbor

  keycloak:
    deploy: true
    version: 0.1.0
    namespace: keycloak

  longhorn:
    deploy: true
    version: 0.0.0
    namespace: longhorn-system

  metallb:
    deploy: true
    version: 0.0.2
    namespace: metallb-system

  traefik:
    deploy: true
    version: 0.0.1
    namespace: gateway

  defaults:
    project: infrastructure
    source:
      repoURL: harbor.wieman.cloud/infrastructure
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true

