environment: 
  hostname: wieman.cloud
  gateway:
    name: traefik-gateway
    listener: websecure
    namespace: gateway
    authentication:
      basicAuth:
        name: basic-auth
        secret:
          name: server-auth-secret

applications:
  website:
    deploy: true
    namespace: website

infrastructure:
  argocd:
    deploy: true
    version: 0.0.0

  certmanager:
    deploy: true
    version: 0.0.0-automate-versioning-49649fe

  externaldns:
    deploy: true
    version: 0.0.0-automate-versioning-49649fe

  harbor:
    deploy: true
    version: 0.0.1

  keycloak:
    deploy: true
    version: 0.1.0

  longhorn:
    deploy: true
    version: 0.0.0

  metallb:
    deploy: true
    version: 0.0.2

  traefik:
    deploy: true
    version: 0.0.1

  server: https://kubernetes.default.svc
  repository: harbor.wieman.cloud/infrastructure
  defaults:
    project: infrastructure
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true

