environment: 
  hostname: wieman.cloud
  gateway:
    name: traefik-gateway
    listener: websecure
    namespace: gateway
    authentication:
      basicAuth:
        name: basic-auth
        secret:
          name: server-auth-secret

applications:
  website:
    deploy: true
    namespace: website

  minecraft:
    deploy: true
    version: 0.3.0-image-build-pipeline-4b78ca7

  server: https://kubernetes.default.svc
  repository: harbor.wieman.cloud/applications
  defaults:
    project: applications
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true


infrastructure:
  argocd:
    deploy: true
    version: 0.1.1

  certmanager:
    deploy: true
    version: 0.0.2

  externaldns:
    deploy: true
    version: 0.0.2

  harbor:
    deploy: true
    version: 1.0.0

  keycloak:
    deploy: true
    version: 0.2.1

  longhorn:
    deploy: true
    version: 0.0.2

  metallb:
    deploy: true
    version: 0.0.4

  traefik:
    deploy: true
    version: 0.1.1

  server: https://kubernetes.default.svc
  repository: harbor.wieman.cloud/infrastructure
  defaults:
    project: infrastructure
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true

images:
  rconcli:
    image: 
      registry: harbor.wieman.cloud
      repository: tools/rconcli
      version: 1.1.0-image-build-pipeline-4b78ca7