environment: 
  hostname: wieman.cloud
  gateway:
    name: traefik-gateway
    listener: websecure
    namespace: gateway
    authentication:
      basicAuth:
        name: basic-auth
        secret:
          name: server-auth-secret

applications:
  website:
    deploy: true
    namespace: website

  minecraft:
    deploy: true
    version: 0.1.1-tweak-storage-0b7fd11

  server: https://kubernetes.default.svc
  repository: harbor.wieman.cloud/applications
  defaults:
    project: applications
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true


infrastructure:
  argocd:
    deploy: true
    version: 0.1.1-tweak-storage-0b7fd11

  certmanager:
    deploy: true
    version: 0.0.2-tweak-storage-0b7fd11

  externaldns:
    deploy: true
    version: 0.0.2-tweak-storage-0b7fd11

  harbor:
    deploy: true
    version: 1.0.0-tweak-storage-0b7fd11

  keycloak:
    deploy: true
    version: 0.2.1-tweak-storage-0b7fd11

  longhorn:
    deploy: true
    version: 0.0.2-tweak-storage-0b7fd11

  metallb:
    deploy: true
    version: 0.0.4-tweak-storage-0b7fd11

  traefik:
    deploy: true
    version: 0.1.1-tweak-storage-0b7fd11

  server: https://kubernetes.default.svc
  repository: harbor.wieman.cloud/infrastructure
  defaults:
    project: infrastructure
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true

