applications:
  argocd:
    path: infrastructure/argocd/chart
    namespace: argocd
  cert-manager:
    path: infrastructure/cert-manager/chart
    namespace: gateway
  external-dns:
    path: infrastructure/external-dns/chart
    namespace: gateway
  harbor:
    path: infrastructure/harbor/chart
    namespace: harbor
  keycloak:
    path: infrastructure/keycloak/chart
    namespace: keycloak
  longhorn:
    path: infrastructure/longhorn/chart
    namespace: longhorn-system
  metallb:
    path: infrastructure/metallb/chart
    namespace: metallb-system
  traefik:
    path: infrastructure/traefik/chart
    namespace: gateway
  wiemansite:
    path: applications/wiemansite
    namespace: default