environment:
  hostname: wieman.cloud
  gateway:
    name: traefik-gateway
    listener: websecure
    namespace: gateway
    authentication:
      basicAuth:
        name: basic-auth
        secret:
          name: server-auth-secret

applications:
  website:
    deploy: true
    namespace: website

  minecraft:
    deploy: true
    version: 0.3.2

  server: https://kubernetes.default.svc
  repository: harbor.wieman.cloud/applications
  defaults:
    project: applications
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true


infrastructure:
  argocd:
    deploy: true
    version: 0.1.4

  certmanager:
    deploy: true
    version: 0.2.1
    certificate:
        email: wiemanboy@gmail.com
        hostnames:
          - "wieman.cloud"
          - "*.wieman.cloud"
          - "wiemanboy.com"
          - "*.wiemanboy.com"
          - "jarnowieman.com"
          - "*.jarnowieman.com"
          - "jarnowieman.nl"
          - "*.jarnowieman.nl"
          - "carnaval.lol"
          - "*.carnaval.lol"

  externaldns:
    deploy: true
    version: 0.0.5

  harbor:
    deploy: true
    version: 1.0.3

  keycloak:
    deploy: true
    version: 0.2.4

  longhorn:
    deploy: true
    version: 0.0.5

  metallb:
    deploy: true
    version: 0.0.7

  traefik:
    deploy: true
    version: 0.1.4

  server: https://kubernetes.default.svc
  repository: harbor.wieman.cloud/infrastructure
  defaults:
    project: infrastructure
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true

images:
  rconcli:
    image:
      registry: harbor.wieman.cloud
      repository: tools/rconcli
      version: 1.1.2
