environment: 
  hostname: wieman.cloud
  gateway:
    name: traefik-gateway
    listener: websecure
    namespace: gateway
    authentication:
      basicAuth:
        name: basic-auth
        secret:
          name: server-auth-secret

applications:
  website:
    deploy: true
    namespace: website

  minecraft:
    deploy: true
    version: 0.3.0-image-build-pipeline-9a0b89f

  server: https://kubernetes.default.svc
  repository: harbor.wieman.cloud/applications
  defaults:
    project: applications
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true


infrastructure:
  argocd:
    deploy: true
    version: 0.1.2-image-build-pipeline-9a0b89f

  certmanager:
    deploy: true
    version: 0.0.3-image-build-pipeline-9a0b89f

  externaldns:
    deploy: true
    version: 0.0.3-image-build-pipeline-9a0b89f

  harbor:
    deploy: true
    version: 1.0.1-image-build-pipeline-9a0b89f

  keycloak:
    deploy: true
    version: 0.2.2-image-build-pipeline-9a0b89f

  longhorn:
    deploy: true
    version: 0.0.3-image-build-pipeline-9a0b89f

  metallb:
    deploy: true
    version: 0.0.5-image-build-pipeline-9a0b89f

  traefik:
    deploy: true
    version: 0.1.2-image-build-pipeline-9a0b89f

  server: https://kubernetes.default.svc
  repository: harbor.wieman.cloud/infrastructure
  defaults:
    project: infrastructure
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true

images:
  rconcli:
    image: 
      registry: harbor.wieman.cloud
      repository: tools/rconcli
      version: 1.1.0-image-build-pipeline-9a0b89f