apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiemansite
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wiemanboy/WieCloud.git
    targetRevision: master
    path: applications/wiemansite
  destination:
    server: https://kubernetes.default.svc
    namespace: wiemansite
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true