apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiecloud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wiemanboy/WieCloud.git
    targetRevision: master
    path: .
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd