applications:
  infrastructure:
    path: applications/infrastructure
    namespace: infrastructure
  gateway:
    path: applications/infrastructure/gateway
    namespace: infrastructure
  load-balancer:
    path: applications/infrastructure/load-balancer
    namespace: infrastructure
  tls:
    path: applications/infrastructure/tls
    namespace: infrastructure
  management:
    path: applications/management  
    namespace: management
  wiemansite:
    path: applications/wiemansite
    namespace: default