applications:
  infrastructure:
    path: applications/infrastructure
    namespace: infrastructure
  management:
    path: applications/management  
    namespace: management
  wiemansite:
    path: applications/wiemansite
    namespace: default