applications:
  argocd:
    path: applications/argocd  
    namespace: argocd
  cert-manager:
    path: applications/cert-manager
    namespace: gateway
  metallb:
    path: applications/metallb
    namespace: metallb
  traefik:
    path: applications/traefik
    namespace: gateway
  wiemansite:
    path: applications/wiemansite
    namespace: default