applications:
  argocd:
    path: applications/argocd  
    namespace: argocd
  cert-manager:
    path: applications/cert-manager
    namespace: cert-manager
  metallb:
    path: applications/metallb
    namespace: metallb
  traefik:
    path: applications/traefik
    namespace: traefik
  wiemansite:
    path: applications/wiemansite
    namespace: default