environment: 
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example
    dns:
      certificate:
        issuer: letsencrypt
        secret: letsencrypt-secret
      hostnames:
        - "wieman.cloud"
        - "*.wieman.cloud"
        - "*.harbor.wieman.cloud"
        - "wiemanboy.com"
        - "*.wiemanboy.com"
        - "jarnowieman.com"
        - "*.jarnowieman.com"
        - "jarnowieman.nl"
        - "*.jarnowieman.nl"
      cloudflare:
        email: wiemanboy@gmail.com
        token:
          secret: 
            name: cloudflare-api-token
            key: api-token

cert-manager:
  crds:
    enabled: true