environment:
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example

certificate:
  issuer: letsencrypt
  secret: letsencrypt-secret
  hostnames:
  - "example.com"
  email: email@example.com
  cloudflare:
    token:
      secret:
        name: cloudflare-api-token
        key: api-token

cert-manager:
  crds:
    enabled: true
