{{- if .Values.infrastructure.externalDns.deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  source:
    chart: external-dns
    repoURL: {{ .Values.infrastructure.repository }}
    targetRevision: {{ .Values.infrastructure.externalDns.version }}
    helm:
      values: |
        environment: {{ toYaml .Values.environment | nindent 8 }}
  destination:
    namespace: gateway
    server: {{ .Values.infrastructure.server }}
  {{- toYaml .Values.infrastructure.defaults | nindent 2 }}
{{- end }}