{{- if .Values.infrastructure.harbor.deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  source:
    chart: harbor
    repoURL: {{ .Values.infrastructure.repository }}
    targetRevision: {{ .Values.infrastructure.harbor.version }}
    helm:
      values: |
        environment: {{ toYaml .Values.environment | nindent 10 }}
        harbor:
          externalURL: harbor.{{ .Values.environment.hostname }}
  destination:
    namespace: harbor
    server: {{ .Values.infrastructure.server }}
  {{- toYaml .Values.infrastructure.defaults | nindent 2 }}
{{- end }}