{{- if .Values.infrastructure.keycloak.deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  source:
    chart: keycloak
    repoURL: {{ .Values.infrastructure.repository }}
    targetRevision: {{ .Values.infrastructure.keycloak.version }}
    helm:
      values: |
        environment: {{ toYaml .Values.environment | nindent 10 }}
  destination:
    namespace: keycloak
    server: {{ .Values.infrastructure.server }}
  {{- toYaml .Values.infrastructure.defaults | nindent 2 }}
{{- end }}