{{- if .Values.infrastructure.rookceph.deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rookceph
  namespace: argocd
spec:
  source:
    chart: rookceph
    repoURL: {{ .Values.infrastructure.repository }}
    targetRevision: {{ .Values.infrastructure.rookceph.version }}
    helm:
      values: |
        environment: {{ toYaml .Values.environment | nindent 10 }}
  destination:
    namespace: rookceph-system
    server: {{ .Values.infrastructure.server }}
  {{- toYaml .Values.infrastructure.defaults | nindent 2 }}
{{- end }}
