{{- $traefikConfig := dict
  "chart" "traefik"
  "repoURL" "https://traefik.github.io/charts"
  "targetRevision" "37.2.0"
  "valueFiles" (list "./traefik.values.yaml")
}}

{{- include "helm.application" (dict "name" "traefik" "config" $traefikConfig) -}}