apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
  namespace: {{ .Values.gateway.namespace }}
spec:
  secretName: {{ .Values.gateway.dns.certificate.secret }}
  dnsNames:
  - "wieman.cloud"
  - "*.wieman.cloud"
  - "*.harbor.wieman.cloud"
  - "wiemanboy.com"
  - "*.wiemanboy.com"
  - "jarnowieman.com"
  - "*.jarnowieman.com"
  - "jarnowieman.nl"
  - "*.jarnowieman.nl"
  issuerRef:
    name: {{ .Values.gateway.dns.certificate.issuer }}
    kind: ClusterIssuer