apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
  namespace: {{ .Values.environment.gateway.namespace }}
spec:
  secretName: {{ .Values.environment.dns.certificate.secret }}
  dnsNames: {{ .Values.environment.dns.hostnames }}
  issuerRef:
    name: {{ .Values.environment.gateway.dns.certificate.issuer }}
    kind: ClusterIssuer