apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.gateway.dns.certificate.issuer }}
spec:
  acme:
    email: wiemanboy@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.gateway.dns.certificate.secret }}
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.gateway.dns.cloudflare.email }}
          apiTokenSecretRef:
            name: {{ .Values.gateway.dns.cloudflare.token.secret.name }}
            key: {{ .Values.gateway.dns.cloudflare.token.secret.key }}
