apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.environment.gateway.authentication.basicAuth.name }}
spec:
  basicAuth:
    secret: {{ .Values.environment.gateway.authentication.basicAuth.secret.name }}