apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: longhorn-frontend
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      sectionName: {{ .Values.gateway.listener }}
      namespace: {{ .Values.gateway.namespace }}

  hostnames:
    - storage.{{ .Values.environment.hostname }}
    
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      backendRefs:
        - name: longhorn-frontend
          namespace: {{ .Values.environment.namespace }}
          port: 80

      filters:
        {{- if .Values.gateway.authentication.enabled }}
        {{- if .Values.gateway.authentication.basicAuth }}
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: {{ .Values.gateway.authentication.basicAuth.name }}
        {{- end }}
        {{- end }}
