apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wiemanboy/WieCloud.git
    targetRevision: master
    path: applications/infrastructure/gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure