apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
spec:
  addresses:
  - {{ .Values.ipconfig.ipv4 }}-{{ .Values.ipconfig.ipv4 }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2
spec:
  ipAddressPools:
  - default-pool
