apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: harbor-route
  annotations:
    external-dns.alpha.kubernetes.io/target: wieman.cloud
spec:
  parentRefs:
    - name: traefik-gateway
      sectionName: websecure
      namespace: gateway

  hostnames:
    - harbor.wieman.cloud

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: harbor-portal
          namespace: harbor
          port: 80

    - matches:
        - path:
            type: PathPrefix
            value: /api/
      backendRefs:
        - name: harbor-core
          namespace: harbor
          port: 80

    - matches:
        - path:
            type: PathPrefix
            value: /service/
      backendRefs:
        - name: harbor-core
          namespace: harbor
          port: 80

    - matches:
        - path:
            type: PathPrefix
            value: /v2/
      backendRefs:
        - name: harbor-core
          namespace: harbor
          port: 80

    - matches:
        - path:
            type: PathPrefix
            value: /chartrepo/
      backendRefs:
        - name: harbor-core
          namespace: harbor
          port: 80

    - matches:
        - path:
            type: PathPrefix
            value: /c/
      backendRefs:
        - name: harbor-core
          namespace: harbor
          port: 80
