apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
  namespace: {{ .Values.environment.gateway.namespace }}
spec:
  secretName: {{ .Values.certificate.secret }}
  dnsNames: {{ toYaml .Values.certificate.hostnames | nindent 4 }}
  issuerRef:
    name: {{ .Values.certificate.issuer }}
    kind: ClusterIssuer
