{{- if .Values.applications.technitium.deploy -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: technitium
  namespace: argocd
spec:
  source:
    chart: technitium
    repoURL: {{ .Values.applications.repository }}
    targetRevision: {{ .Values.applications.technitium.version }}
    helm:
      values: |
        environment: {{ toYaml .Values.environment | nindent 10 }}
  destination:
    namespace: technitium
    server: {{ .Values.applications.server }}
  {{- toYaml .Values.applications.defaults | nindent 2 }}
{{- end }}