environment: 
  name: prod
  hostname: wieman.cloud
  namespace: keycloak

gateway:
  name: traefik-gateway
  listener: websecure
  namespace: gateway

realm:
  clients:
    defaults:
      enabled: true
      alwaysDisplayInConsole: true
      clientAuthenticatorType: client-secret
      standardFlowEnabled: true
      directAccessGrantsEnabled: true
      serviceAccountsEnabled: true
      protocol: openid-connect
      defaultClientScopes:
        - web-origins
        - service_account
        - acr
        - profile
        - roles
        - groups
        - basic
        - email
      optionalClientScopes:
        - address
        - phone
        - organization
        - offline_access
        - microprofile-jwt

keycloak:
  db:
    vendor: postgres
    host: postgres-db
    username:
      secret: keycloak-db-secret
      key: username
    password:
      secret: keycloak-db-secret
      key: password