environment: 
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example

keycloak:
  db:
    vendor: postgres
    host: postgres-db
    username:
      secret: keycloak-db-secret
      key: username
    password:
      secret: keycloak-db-secret
      key: password