environment: 
  name: prod
  hostname: wieman.cloud
  namespace: argocd

test: test-value

gateway:
  name: traefik-gateway
  listener: websecure
  namespace: gateway

argo-cd:
  configs:
    params:
      server.insecure: true
    cm:
      exec.enabled: true