environment: 
  hostname: example.com
  gateway:
    name: example-gateway
    listener: web-example
    namespace: example

argo-cd:
  configs:
    params:
      server.insecure: true
    cm:
      admin.enabled: "false"
      url: https://argo.example.com
      exec.enabled: true
      oidc.config: "overwritten"
    rbac:
      policy.default: role:readonly
      policy.csv: |
        g, /infra/admin, role:admin
