environment: 
  name: prod
  hostname: wieman.cloud
  namespace: argocd

gateway:
  name: traefik-gateway
  listener: websecure
  namespace: gateway

argo-cd:
  configs:
    params:
      server.insecure: true
    cm:
      url: https://argocd.wieman.cloud
      exec.enabled: true
      oidc.config: |
        name: Keycloak
        issuer: https://keycloak.wieman.cloud/realms/infrastructure
        clientID: argocd
        clientSecret: $oidc.keycloak.clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]