apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: harbor-route
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      sectionName: {{ .Values.gateway.listener }}
      namespace: {{ .Values.gateway.namespace }}

  hostnames:
    - harbor.{{ .Values.environment.hostname }}

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: harbor-portal
          namespace: {{ .Values.environment.namespace }}
          port: 80

    - matches:
        - path:
            type: PathPrefix
            value: /api/
      backendRefs:
        - name: harbor-core
          namespace: {{ .Values.environment.namespace }}
          port: 80

    - matches:
        - path:
            type: PathPrefix
            value: /service/
      backendRefs:
        - name: harbor-core
          namespace: {{ .Values.environment.namespace }}
          port: 80

    - matches:
        - path:
            type: PathPrefix
            value: /v2/
      backendRefs:
        - name: harbor-core
          namespace: {{ .Values.environment.namespace }}
          port: 80

    - matches:
        - path:
            type: PathPrefix
            value: /chartrepo/
      backendRefs:
        - name: harbor-core
          namespace: {{ .Values.environment.namespace }}
          port: 80

    - matches:
        - path:
            type: PathPrefix
            value: /c/
      backendRefs:
        - name: harbor-core
          namespace: {{ .Values.environment.namespace }}
          port: 80
