name: Build keycloak

on:
  push:
    branches:
    - master
    paths:
    - infrastructure/keycloak/chart**
    - .github/workflows/build_keycloak.yaml
    - .github/workflows/build.yaml
    - pipeline/build/scripts/**
  pull_request:
    branches:
    - master
    types:
    - ready_for_review
    - synchronize
    paths:
    - infrastructure/keycloak/chart**
    - .github/workflows/build_keycloak.yaml
    - .github/workflows/build.yaml
    - pipeline/build/scripts/**
  workflow_dispatch:


jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      chart_name: keycloak
      chart_path: infrastructure/keycloak/chart
      registry: oci://harbor.wieman.cloud
      repository: infrastructure
    secrets:
      registry_username: ${{ secrets.OCI_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.OCI_REGISTRY_PASSWORD }}
