name: Build gateway

on:
  push:
    branches:
      - master
    paths:
      - infrastructure/traefik/chart**
      - .github/workflows/build_gateway.yaml
      - .github/workflows/package_push.yaml
      - pipeline/build/scripts/**
  pull_request:
    branches:
      - master
    paths:
      - infrastructure/traefik/chart**
      - .github/workflows/build_gateway.yaml
      - .github/workflows/package_push.yaml
      - pipeline/build/scripts/**

jobs:
  deploy:
    uses: ./.github/workflows/package_push.yaml
    with:
      chart_name: gateway
      chart_path: infrastructure/traefik/chart
      registry: oci://harbor.wieman.cloud
      repository: infrastructure
    secrets:
      registry_username: ${{ secrets.OCI_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.OCI_REGISTRY_PASSWORD }}
