name: Build load-balancer

on:
  push:
    branches:
      - master
    paths:
      - infrastructure/metallb/chart**
      - .github/workflows/build_load-balancer.yaml
      - .github/workflows/package_push.yaml
      - pipeline/build/scripts/**
  pull_request:
    branches:
      - master
    paths:
      - infrastructure/metallb/chart**
      - .github/workflows/build_load-balancer.yaml
      - .github/workflows/package_push.yaml
      - pipeline/build/scripts/**

jobs:
  deploy:
    uses: ./.github/workflows/package_push.yaml
    with:
      chart_name: load-balancer
      chart_path: infrastructure/metallb/chart
      registry: oci://harbor.wieman.cloud
      repository: infrastructure
    secrets:
      registry_username: ${{ secrets.OCI_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.OCI_REGISTRY_PASSWORD }}
