name: Build metallb

on:
  push:
    branches:
      - master
    paths:
      - infrastructure/metallb/chart**
      - .github/workflows/build_metallb.yaml
      - .github/workflows/package_push.yaml
      - pipeline/build/scripts/**
  pull_request:
    branches:
      - master
    paths:
      - infrastructure/metallb/chart**
      - .github/workflows/build_metallb.yaml
      - .github/workflows/package_push.yaml
      - pipeline/build/scripts/**

jobs:
  package_and_push:
    name: Package and push
    uses: ./.github/workflows/package_push.yaml
    with:
      chart_name: metallb
      chart_path: infrastructure/metallb/chart
      registry: harbor.wieman.cloud
      repository: infrastructure
    secrets:
      registry_username: ${{ secrets.OCI_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.OCI_REGISTRY_PASSWORD }}
