name: Build wiecloud

on:
  push:
    branches:
      - master
    paths:
      - wiecloud/chart**
      - .github/workflows/build_wiecloud.yaml
      - .github/workflows/package_push.yaml
      - pipeline/build/scripts/**
  pull_request:
    branches:
      - master
    paths:
      - wiecloud/chart**
      - .github/workflows/build_wiecloud.yaml
      - .github/workflows/package_push.yaml
      - pipeline/build/scripts/**

jobs:
  package_and_push:
    name: Package and push
    uses: ./.github/workflows/package_push.yaml
    with:
      chart_name: wiecloud
      chart_path: wiecloud/chart
      registry: oci://harbor.wieman.cloud
      repository: wiecloud
    secrets:
      registry_username: ${{ secrets.OCI_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.OCI_REGISTRY_PASSWORD }}
