name: Build harbor

on:
  push:
    branches:
    - master
    paths:
    - infrastructure/harbor/chart**
    - .github/workflows/build_harbor.yaml
    - .github/workflows/build.yaml
    - pipeline/build/scripts/**
  pull_request:
    branches:
    - master
    paths:
    - infrastructure/harbor/chart**
    - .github/workflows/build_harbor.yaml
    - .github/workflows/build.yaml
    - pipeline/build/scripts/**
  workflow_dispatch:


jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      chart_name: harbor
      chart_path: infrastructure/harbor/chart
      registry: oci://harbor.wieman.cloud
      repository: infrastructure
    secrets:
      registry_username: ${{ secrets.OCI_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.OCI_REGISTRY_PASSWORD }}
      app_client_id: ${{ secrets.APP_CLIENT_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
