name: Build Base

on:
  push:
    branches:
      - master
    paths:
      - infrastructure/_base/chart**
      - .github/workflows/build__base.yaml
      - .github/workflows/package_push.yaml
      - pipeline/build/scripts/**
  pull_request:
    branches:
      - master
    paths:
      - infrastructure/_base/chart**
      - .github/workflows/build__base.yaml
      - .github/workflows/package_push.yaml
      - pipeline/build/scripts/**

jobs:
  deploy:
    uses: ./.github/workflows/package_push.yaml
    with:
      chart_path: infrastructure/_base/chart
      registry: oci://harbor.wieman.cloud
      repository: charts
    secrets:
      registry_username: ${{ secrets.OCI_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.OCI_REGISTRY_PASSWORD }}
