name: Build argocd

on:
  push:
    branches:
      - master
    paths:
      - infrastructure/argocd/chart**
      - .github/workflows/build_argocd.yaml
      - .github/workflows/package_push.yaml
      - pipeline/build/scripts/**
  pull_request:
    branches:
      - master
    paths:
      - infrastructure/argocd/chart**
      - .github/workflows/build_argocd.yaml
      - .github/workflows/package_push.yaml
      - pipeline/build/scripts/**

jobs:
  package_and_push:
    name: Package and push
    uses: ./.github/workflows/package_push.yaml
    with:
      chart_name: argocd
      chart_path: infrastructure/argocd/chart
      registry: oci://harbor.wieman.cloud
      repository: infrastructure
    secrets:
      registry_username: ${{ secrets.OCI_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.OCI_REGISTRY_PASSWORD }}
