name: Build keycloak

on:
  pull_request:
    branches:
    - master
    paths:
    - infrastructure/keycloak/chart**
    - .github/workflows/build_keycloak.yaml
    - .github/workflows/build.yaml
    - pipeline/build/scripts/**

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      chart_name: keycloak
      chart_path: infrastructure/keycloak/chart
      registry: oci://harbor.wieman.cloud
      repository: infrastructure
    secrets:
      registry_username: ${{ secrets.OCI_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.OCI_REGISTRY_PASSWORD }}
      app_client_id: ${{ secrets.APP_CLIENT_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
