name: Build technitium

on:
  pull_request:
    branches:
    - master
    paths:
    - applications/technitium/chart**
    - .github/workflows/build_technitium.yaml
    - .github/workflows/build.yaml
    - pipeline/build/scripts/**

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      chart_name: technitium
      chart_path: applications/technitium/chart
      registry: oci://harbor.wieman.cloud
      repository: applications
    secrets:
      registry_username: ${{ secrets.OCI_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.OCI_REGISTRY_PASSWORD }}
      app_client_id: ${{ secrets.APP_CLIENT_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
