name: Build rcon-cli

on:
  pull_request:
    branches:
    - master
    paths:
    - applications/minecraft/tools/rcon-cli**
    - .github/workflows/image_build_rcon-cli.yaml
    - .github/workflows/image_build.yaml
    - pipeline/build/scripts/image/**

jobs:
  build:
    name: Build
    uses: ./.github/workflows/image_build.yaml
    with:
      image_name: rcon-cli
      image_path: applications/minecraft/tools/rcon-cli
      registry: harbor.wieman.cloud
      repository: tools
    secrets:
      registry_username: ${{ secrets.OCI_REGISTRY_USERNAME }}
      registry_password: ${{ secrets.OCI_REGISTRY_PASSWORD }}
      app_client_id: ${{ secrets.APP_CLIENT_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
